# Generated by Django 6.0.7 on 2026-07-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Skill',
                'verbose_name_plural': 'About Skills',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('job', 'Job / Work Experience'), ('education', 'Education'), ('achievements', 'Achievements Box')], default='job', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('org_url', models.URLField(blank=True)),
                ('period', models.CharField(help_text="E.g. 'Present' or '2022-2026'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Career Entry',
                'verbose_name_plural': 'Career Entries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="E.g. 'FRONTEND'", max_length=80)),
                ('subtitle', models.CharField(help_text="E.g. 'Interface'", max_length=80)),
                ('description', models.TextField()),
                ('tags', models.TextField(help_text='Comma-separated skill tags')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expertise Area',
                'verbose_name_plural': 'Expertise Areas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nahidul Arafat', max_length=100)),
                ('first_name', models.CharField(default='NAHIDUL', max_length=50)),
                ('last_name', models.CharField(default='ARAFAT', max_length=50)),
                ('tagline', models.CharField(default='A Passionate', max_length=100)),
                ('role_line1', models.CharField(default='FULL STACK', max_length=80)),
                ('role_line2', models.CharField(default='ENGINEER', max_length=80)),
                ('email', models.EmailField(default='nahidularaf@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+880 1974-337424', max_length=30)),
                ('github_url', models.URLField(blank=True, default='https://github.com/nahidularafat')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/nahidul-arafat-9ab8332ba')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_url', models.CharField(default='/resume.pdf', max_length=255)),
                ('copyright_year', models.CharField(default='2025', max_length=10)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Display number e.g. '01'", max_length=5)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(help_text="E.g. 'Corporate Website'", max_length=100)),
                ('tools', models.CharField(help_text='Comma-separated tools list', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Project screenshot. Leave blank to use static placeholder.', null=True, upload_to='projects/')),
                ('image_static_path', models.CharField(default='/images/placeholder.webp', help_text='Fallback static path if no image uploaded', max_length=255)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('twitter', 'X / Twitter'), ('instagram', 'Instagram'), ('other', 'Other')], max_length=30)),
                ('label', models.CharField(help_text="Display label, e.g. 'Github'", max_length=50)),
                ('url', models.URLField()),
                ('icon_name', models.CharField(help_text='react-icons fa6 key, e.g. FaGithub, FaLinkedinIn, FaCodepen', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('value', models.CharField(help_text="Display value e.g. '32+' or '500+'", max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tech Category',
                'verbose_name_plural': 'Tech Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(help_text='Bold part of the achievement', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Rest of the achievement text')),
                ('order', models.PositiveIntegerField(default=0)),
                ('career_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='portfolio.careerentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon_url', models.URLField(help_text='CDN URL to the devicon SVG')),
                ('color', models.CharField(help_text='Hex glow color e.g. #22C55E', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='portfolio.techcategory')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order'],
            },
        ),
    ]
