# Generated by Django 6.0.7 on 2026-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="E.g. 'Frontend'", max_length=80)),
                ('skills', models.CharField(help_text="Comma-separated skills, e.g. 'React, HTML, CSS, Tailwind'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expertise Item',
                'verbose_name_plural': 'Expertise Items',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='A passionate Full Stack Engineer specializing in Python, Django, and React. I build scalable web platforms, AI-powered agents, and real-world mobile applications.', help_text='Short bio / summary shown on the portfolio or CV.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='codechef_url',
            field=models.URLField(blank=True, default='https://www.codechef.com/users/nahidularaf'),
        ),
        migrations.AddField(
            model_name='profile',
            name='codeforces_url',
            field=models.URLField(blank=True, default='https://codeforces.com/profile/Arafat0012'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=100),
        ),
    ]
